## House Prices (Estructura de los datos)

In [19]:
from house_prices_mlops.pipeline import load_stage
from house_prices_mlops.data_tracker import DataTracker


df_hp = load_stage("train")
tracker = DataTracker.load(df_hp)

### Shape

In [20]:
#Shape
display(df_hp.shape)

(1168, 81)

### Variables Types

In [21]:
display(tracker.profile)

,var,data_type,variable_type,unique_count,missing_count,missing_pct,zero_count,zero_pct,min,max,mean,median,std,skewness,kurtosis
0,Id,int64,identifier,1168,0,0.000000,0.0,0.0,1.0,1460.0,730.904966,732.5,425.369088,0.000920,-1.215850
1,MSSubClass,int64,nominal,15,0,0.000000,0.0,0.0,20.0,190.0,56.849315,50.0,42.531862,1.438804,1.698354
2,MSZoning,object,nominal,5,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,LotFrontage,float64,continuous,107,217,18.578767,0.0,0.0,21.0,313.0,70.343849,70.0,24.897021,2.406787,19.454319
4,LotArea,int64,continuous,890,0,0.000000,0.0,0.0,1300.0,215245.0,10689.642123,9600.0,10759.366198,11.958088,186.444082
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
76,MoSold,int64,temporal,12,0,0.000000,0.0,0.0,1.0,12.0,6.356164,6.0,2.670707,0.241761,-0.371218
77,YrSold,int64,temporal,5,0,0.000000,0.0,0.0,2006.0,2010.0,2007.818493,2008.0,1.322639,0.082593,-1.187097
78,SaleType,object,nominal,9,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,SaleCondition,object,nominal,6,0,0.000000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,SalePrice,int64,continuous,571,0,0.000000,0.0,0.0,34900.0,745000.0,181441.541952,165000.0,77263.583862,1.743129,5.475315

In [22]:
# DU — Structure: revisión de naturaleza y representación técnica

structure = tracker.profile[
    ["var", "variable_type", "data_type", "unique_count"]
].copy()

variable_groups = [
    "continuous",
    "discrete",
    "ordinal",
    "nominal",
    "temporal",
    "identifier"
]

for kind in variable_groups:
    group = structure[structure["variable_type"] == kind]
    print(f"{kind.upper()} — {len(group)} variables")
    display(group.reset_index(drop=True))

CONTINUOUS — 20 variables

              var variable_type data_type  unique_count
0     LotFrontage    continuous   float64           107
1         LotArea    continuous     int64           890
2      MasVnrArea    continuous   float64           286
3      BsmtFinSF1    continuous     int64           549
4      BsmtFinSF2    continuous     int64           118
5       BsmtUnfSF    continuous     int64           685
6     TotalBsmtSF    continuous     int64           630
7        1stFlrSF    continuous     int64           657
8        2ndFlrSF    continuous     int64           361
9    LowQualFinSF    continuous     int64            20
10      GrLivArea    continuous     int64           734
11     GarageArea    continuous     int64           394
12     WoodDeckSF    continuous     int64           244
13    OpenPorchSF    continuous     int64           188
14  EnclosedPorch    continuous     int64            98
15      3SsnPorch    continuous     int64            17
16    ScreenPorch    continuous     int64            66
17       PoolArea    continuous     int64             7
18        MiscVal    continuous     int64            19
19      SalePrice    continuous     int64           571

DISCRETE — 9 variables

            var variable_type data_type  unique_count
0  BsmtFullBath      discrete     int64             4
1  BsmtHalfBath      discrete     int64             3
2      FullBath      discrete     int64             4
3      HalfBath      discrete     int64             3
4  BedroomAbvGr      discrete     int64             8
5  KitchenAbvGr      discrete     int64             4
6  TotRmsAbvGrd      discrete     int64            12
7    Fireplaces      discrete     int64             4
8    GarageCars      discrete     int64             5

ORDINAL — 22 variables

             var variable_type data_type  unique_count
0       LotShape       ordinal    object             4
1      Utilities       ordinal    object             2
2      LandSlope       ordinal    object             3
3    OverallQual       ordinal     int64            10
4    OverallCond       ordinal     int64             9
5      ExterQual       ordinal    object             4
6      ExterCond       ordinal    object             5
7       BsmtQual       ordinal    object             4
8       BsmtCond       ordinal    object             4
9   BsmtExposure       ordinal    object             4
10  BsmtFinType1       ordinal    object             6
11  BsmtFinType2       ordinal    object             6
12     HeatingQC       ordinal    object             5
13   KitchenQual       ordinal    object             4
14    Functional       ordinal    object             7
15   FireplaceQu       ordinal    object             5
16  GarageFinish       ordinal    object             3
17    GarageQual       ordinal    object             5
18    GarageCond       ordinal    object             5
19    PavedDrive       ordinal    object             3
20        PoolQC       ordinal    object             3
21         Fence       ordinal    object             4

NOMINAL — 24 variables

              var variable_type data_type  unique_count
0      MSSubClass       nominal     int64            15
1        MSZoning       nominal    object             5
2          Street       nominal    object             2
3           Alley       nominal    object             2
4     LandContour       nominal    object             4
5       LotConfig       nominal    object             5
6    Neighborhood       nominal    object            25
7      Condition1       nominal    object             9
8      Condition2       nominal    object             8
9        BldgType       nominal    object             5
10     HouseStyle       nominal    object             8
11      RoofStyle       nominal    object             6
12       RoofMatl       nominal    object             7
13    Exterior1st       nominal    object            15
14    Exterior2nd       nominal    object            16
15     MasVnrType       nominal    object             3
16     Foundation       nominal    object             6
17        Heating       nominal    object             6
18     CentralAir       nominal    object             2
19     Electrical       nominal    object             4
20     GarageType       nominal    object             6
21    MiscFeature       nominal    object             4
22       SaleType       nominal    object             9
23  SaleCondition       nominal    object             6

TEMPORAL — 5 variables

            var variable_type data_type  unique_count
0     YearBuilt      temporal     int64           111
1  YearRemodAdd      temporal     int64            61
2   GarageYrBlt      temporal   float64            94
3        MoSold      temporal     int64            12
4        YrSold      temporal     int64             5

IDENTIFIER — 1 variables

  var variable_type data_type  unique_count
0  Id    identifier     int64          1168

### Cardinality (Naturaleza de la variable)

In [23]:
# Cardinalidad de variables categóricas

cardinality_review = tracker.profile[
    tracker.profile['variable_type'].isin([
        'nominal',
        'ordinal'
    ])
][
    ['var', 'data_type', 'variable_type', 'unique_count']
].sort_values(
    'unique_count',
    ascending=False
)

display(cardinality_review)

              var data_type variable_type  unique_count
12   Neighborhood    object       nominal            25
24    Exterior2nd    object       nominal            16
23    Exterior1st    object       nominal            15
1      MSSubClass     int64       nominal            15
17    OverallQual     int64       ordinal            10
13     Condition1    object       nominal             9
18    OverallCond     int64       ordinal             9
78       SaleType    object       nominal             9
16     HouseStyle    object       nominal             8
14     Condition2    object       nominal             8
22       RoofMatl    object       nominal             7
55     Functional    object       ordinal             7
21      RoofStyle    object       nominal             6
35   BsmtFinType2    object       ordinal             6
58     GarageType    object       nominal             6
33   BsmtFinType1    object       ordinal             6
39        Heating    object       nominal             6
29     Foundation    object       nominal             6
79  SaleCondition    object       nominal             6
40      HeatingQC    object       ordinal             5
15       BldgType    object       nominal             5
10      LotConfig    object       nominal             5
2        MSZoning    object       nominal             5
63     GarageQual    object       ordinal             5
57    FireplaceQu    object       ordinal             5
64     GarageCond    object       ordinal             5
28      ExterCond    object       ordinal             5
7        LotShape    object       ordinal             4
8     LandContour    object       nominal             4
74    MiscFeature    object       nominal             4
53    KitchenQual    object       ordinal             4
73          Fence    object       ordinal             4
42     Electrical    object       nominal             4
31       BsmtCond    object       ordinal             4
27      ExterQual    object       ordinal             4
32   BsmtExposure    object       ordinal             4
30       BsmtQual    object       ordinal             4
11      LandSlope    object       ordinal             3
72         PoolQC    object       ordinal             3
60   GarageFinish    object       ordinal             3
65     PavedDrive    object       ordinal             3
25     MasVnrType    object       nominal             3
9       Utilities    object       ordinal             2
5          Street    object       nominal             2
6           Alley    object       nominal             2
41     CentralAir    object       nominal             2

In [ ]:
tracker.add_finding(key='ms_subclass_representation', 
    var="MSSubClass",
    stage="DU_Structure",
    finding=(
        "Variable nominal representada mediante códigos enteros. "
        "Su tratamiento en DP debe preservar el carácter categórico."
    )
)
tracker.save()